#!/usr/bin/env python3
"""Generate runtime/mesh/hes_system.h from targets/hetero/system.py.

The bare-metal runtime and the GVSoC board have to agree on every address in
the SoC. Rather than write them twice, the C header is generated from the
Python machine model, and the cluster peripheral register offsets in that
model are checked against the header GVSoC generates from its own register
description -- so a GVSoC update that moves a register is a build failure
here rather than a store that quietly lands on the wrong register.

  python pipeline/gen_system_header.py            # write the header
  python pipeline/gen_system_header.py --check    # fail if it is out of date
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "targets"))

from hetero import memsys, system  # noqa: E402

MESH = ROOT / "runtime" / "mesh"
HEADER = MESH / "hes_system.h"

# GVSoC generates one of these per cluster peripheral variant while building.
GENERATED_REGMAPS = {
    "snitch": ROOT / "deps/gvsoc/build/engine/pulp/snitch/snitch_cluster/cluster_periph_gvsoc.h",
    "spatz": ROOT / "deps/gvsoc/build/engine/pulp/snitch/snitch_cluster/spatz/cluster_periph_gvsoc.h",
}


def parse_regmap(path: Path) -> dict:
    """Register name -> offset, from a GVSoC-generated regmap header.

    Each register is a class whose constructor body sets `this->name` and
    `this->offset` in that order.
    """
    text = path.read_text()
    return {
        m.group(1): int(m.group(2), 0)
        for m in re.finditer(r'this->name\s*=\s*"([A-Z0-9_]+)";\s*\n\s*'
                             r'this->offset\s*=\s*(0x[0-9a-fA-F]+|\d+);', text)
    }


def verify_offsets() -> str:
    """Check each cluster's derived peripheral offsets against GVSoC's regmap.

    The two variants declare a different NumPerfCounters, so the scalar
    registers sit at different offsets in each -- which is exactly the kind of
    thing this check exists to catch.
    """
    checked = []
    for cluster in system.CLUSTERS:
        path = GENERATED_REGMAPS[cluster.name]
        if not path.exists():
            continue
        regs = parse_regmap(path)
        expected = {
            "CL_CLINT_SET": cluster.cl_clint_set_offset,
            "CL_CLINT_CLEAR": cluster.cl_clint_clear_offset,
            "HW_BARRIER": cluster.hw_barrier_offset,
            "PERF_COUNTER_ENABLE_0": cluster.perf_counter_enable_offset,
            "HART_SELECT_0": cluster.hart_select_offset,
            "PERF_COUNTER_0": cluster.perf_counter_offset,
        }
        for name, want in expected.items():
            if name not in regs:
                raise SystemExit(
                    f"error: {name} is missing from {path.relative_to(ROOT)} -- the "
                    f"{cluster.name} cluster peripheral register map changed; update "
                    f"targets/hetero/system.py")
            if regs[name] != want:
                raise SystemExit(
                    f"error: {cluster.name} cluster: {name} is at 0x{regs[name]:x} in "
                    f"{path.relative_to(ROOT)} but targets/hetero/system.py derives "
                    f"0x{want:x} -- update the model")
        # The counter count itself is what the offsets are derived from, so
        # check it directly too.
        n = sum(1 for name in regs if name.startswith("PERF_COUNTER_ENABLE_"))
        if n != cluster.nb_perf_counters:
            raise SystemExit(
                f"error: {cluster.name} cluster has {n} performance counters in "
                f"{path.relative_to(ROOT)}, not {cluster.nb_perf_counters}")
        checked.append(cluster.name)

    if not checked:
        return ("cluster peripheral offsets UNVERIFIED (GVSoC not built yet; "
                "they are checked against its generated regmap once it is)")
    return f"peripheral offsets verified against GVSoC's regmap for: {', '.join(checked)}"


def render(note: str) -> str:
    out = []
    w = out.append

    w("/* Generated by pipeline/gen_system_header.py from targets/hetero/system.py.")
    w(" * Do not edit: change the machine model and regenerate.")
    w(" *")
    w(f" * {note}")
    w(" */")
    w("#ifndef HES_SYSTEM_H")
    w("#define HES_SYSTEM_H")
    w("")

    def section(title):
        w("")
        w(f"/* --- {title} " + "-" * max(0, 66 - len(title)) + " */")
        w("")

    def define(name, value, comment=None, hex_width=None):
        if hex_width:
            val = f"0x{value:0{hex_width}x}u"
        elif isinstance(value, int) and value >= 0x1000:
            val = f"0x{value:08x}u"
        else:
            val = str(value)
        line = f"#define {name:<32} {val}"
        w(f"{line}  /* {comment} */" if comment else line)

    section("Main memory")
    define("HES_HBM_BASE", system.HBM_BASE)
    define("HES_HBM_SIZE", system.HBM_SIZE)
    define("HES_DRAM_LATENCY", memsys.DRAM_LATENCY, "cycles, main memory")

    section("Per-ELF load windows")
    for tag, base, size in (
        ("HOST", system.HOST_LOAD_BASE, system.HOST_LOAD_SIZE),
        ("SNITCH", system.SNITCH_LOAD_BASE, system.SNITCH_LOAD_SIZE),
        ("SPATZ", system.SPATZ_LOAD_BASE, system.SPATZ_LOAD_SIZE),
    ):
        define(f"HES_{tag}_LOAD_BASE", base)
        define(f"HES_{tag}_LOAD_SIZE", size)

    section("Host peripherals")
    define("HES_STDOUT_BASE", system.STDOUT_BASE)
    define("HES_CONTROL_REGS_BASE", system.CONTROL_REGS_BASE)
    define("HES_DRAM_BASE", system.DRAM_BASE)
    define("HES_HOST_HARTID", system.HOST_HARTID)
    define("HES_HOST_SCRATCH", system.HOST_SCRATCH_BASE,
           "free main memory past the host's image")
    define("HES_HOST_SCRATCH_SIZE", system.HOST_SCRATCH_SIZE)

    section("Cluster address map (relative to a cluster base)")
    define("HES_TCDM_OFFSET", system.TCDM_OFFSET)
    define("HES_TCDM_SIZE", system.TCDM_SIZE)
    define("HES_PERIPHERAL_OFFSET", system.PERIPHERAL_OFFSET)
    define("HES_ZERO_MEM_OFFSET", system.ZERO_MEM_OFFSET)

    section("Cluster peripheral registers")
    w("/* Offsets from a cluster's peripheral base. The two variants declare a")
    w(" * different NumPerfCounters, so the scalar registers do not sit at the")
    w(" * same offset in both -- always use the ones for the cluster at hand. */")
    define("HES_CLUSTER_IRQ", system.CLUSTER_IRQ, "IRQ CL_CLINT_SET raises")
    w("/* A readable peripheral register, at the same offset in both\n   * variants, used only to check that the path answers. */")
    define("HES_PERIPH_PERF_COUNTER_PROBE", 0, hex_width=3)

    section("The clusters")
    for c in system.CLUSTERS:
        tag = c.name.upper()
        w(f"/* {c.name}: {c.nb_core} cores, "
          f"{'Snitch + Spatz VPU' if c.use_spatz else 'Snitch + FP subsystem (Xssr/Xfrep)'} */")
        define(f"HES_{tag}_BASE", c.base)
        define(f"HES_{tag}_TCDM", c.tcdm_base)
        define(f"HES_{tag}_PERIPH", c.peripheral_base)
        define(f"HES_{tag}_NB_CORE", c.nb_core)
        define(f"HES_{tag}_DMA_CORE", c.dma_core)
        define(f"HES_{tag}_CTRL_CORE", c.ctrl_core)
        define(f"HES_{tag}_FIRST_HARTID", c.first_hartid)
        define(f"HES_{tag}_LOAD_SCRATCH", c.scratch_base,
               "free main memory past this cluster's image")
        define(f"HES_{tag}_LOAD_SCRATCH_SIZE", c.scratch_size)
        define(f"HES_{tag}_CL_CLINT_SET", c.cl_clint_set_offset, hex_width=3)
        define(f"HES_{tag}_CL_CLINT_CLEAR", c.cl_clint_clear_offset, hex_width=3)
        define(f"HES_{tag}_HW_BARRIER", c.hw_barrier_offset, hex_width=3)
        define(f"HES_{tag}_PERF_COUNTER", c.perf_counter_offset, hex_width=3)
        define(f"HES_{tag}_PERF_COUNTER_ENABLE", c.perf_counter_enable_offset, hex_width=3)
        define(f"HES_{tag}_NB_PERF_COUNTERS", c.nb_perf_counters)
        w("")

    section("Job mailbox")
    define("HES_MAILBOX_OFFSET", system.MAILBOX_OFFSET)
    define("HES_MAILBOX_SIZE", system.MAILBOX_SIZE, hex_width=3)
    define("HES_MAILBOX_MAX_ARGS", system.MAILBOX_MAX_ARGS)
    define("HES_CLUSTER_STACK_SIZE", system.CLUSTER_STACK_SIZE)

    section("Engine ids")
    for eid, name in sorted(system.ENGINE_NAMES.items()):
        define(f"HES_ENGINE_{name.upper()}", eid)
    define("HES_NB_ENGINES", len(system.ENGINE_NAMES))

    w("")
    w("#endif /* HES_SYSTEM_H */")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Linker scripts
#
# Generated from the same model as the header so a section can never be linked
# outside the window the board maps for it.


_GENERATED_BY = """/* Generated by pipeline/gen_system_header.py from targets/hetero/system.py.
 * Do not edit: change the machine model and regenerate.
 */"""


def host_linker() -> str:
    """CVA6 host: everything in main memory.

    The heap and the stack are plain symbols rather than NOLOAD sections. A
    NOLOAD section is NOBITS in the ELF, and GVSoC's loader zero-fills those --
    a 64 MiB heap costs ~100k simulated cycles and seconds of wall time before
    the first instruction runs, on every single run. Nothing needs them zeroed:
    _sbrk hands out the heap and the stack grows down into its own space.
    """
    return f"""{_GENERATED_BY}
OUTPUT_ARCH(riscv)
ENTRY(_start)

MEMORY
{{
  RAM (rwx) : ORIGIN = 0x{system.HOST_LOAD_BASE:08x}, LENGTH = 0x{system.HOST_LOAD_SIZE:08x}
}}

SECTIONS
{{
  .text : {{
    KEEP(*(.text.init))
    *(.text*)
  }} > RAM

  .rodata : {{ *(.rodata*) *(.srodata*) }} > RAM

  . = ALIGN(8);
  .data : {{ *(.data*) }} > RAM

  . = ALIGN(8);
  __global_pointer$ = . + 0x800;
  .sdata : {{ *(.sdata*) }} > RAM

  /* LMA == VMA, so crt0 skips the copy loop. */
  __data_start = 0;
  __data_end = 0;
  __data_load_start = 0;

  . = ALIGN(8);
  __bss_start = .;
  .sbss : {{ *(.sbss*) }} > RAM
  .bss  : {{ *(.bss*) *(COMMON) }} > RAM
  . = ALIGN(8);
  __bss_end = .;

  /* Heap and stack: symbols only, so no zero-filled program header. */
  . = ALIGN(16);
  __heap_start = .;
  __heap_end = __heap_start + 0x{system.HOST_HEAP_SIZE:x};
  __stack_top = __heap_end + 0x{system.HOST_STACK_SIZE:x};

  ASSERT(__stack_top <= ORIGIN(RAM) + LENGTH(RAM),
         "host image overflows its window in main memory")
}}
"""


def cluster_linker(cluster) -> str:
    """A cluster: code in its main-memory window, data and stacks in TCDM.

    The first HES_MAILBOX_SIZE bytes of TCDM are the job mailbox the host
    writes, so TCDM here starts above it. Each core gets its own stack at the
    top of TCDM; whatever is left between .bss and the stacks is the scratch
    the DMA stages tiles into.
    """
    tcdm_base = cluster.tcdm_base + system.MAILBOX_SIZE
    tcdm_len = system.TCDM_SIZE - system.MAILBOX_SIZE
    stacks = cluster.nb_core * system.CLUSTER_STACK_SIZE
    return f"""{_GENERATED_BY}
/* Cluster '{cluster.name}': {cluster.nb_core} cores, TCDM 0x{cluster.tcdm_base:08x}, \
code at 0x{cluster.load_base:08x}. */
OUTPUT_ARCH(riscv)
ENTRY(_start)

MEMORY
{{
  ROM  (rx) : ORIGIN = 0x{cluster.load_base:08x}, LENGTH = 0x{cluster.load_size:08x}
  TCDM (rw) : ORIGIN = 0x{tcdm_base:08x}, LENGTH = 0x{tcdm_len:08x}
}}

SECTIONS
{{
  .text : {{
    KEEP(*(.text.init))
    *(.text*)
  }} > ROM

  /* Data runs in TCDM but is loaded in main memory; crt0 copies it. The ELF
   * loader cannot burst-write the banked TCDM. */
  . = ALIGN(8);
  .data : {{
    __data_start = .;
    *(.rodata*) *(.srodata*)
    . = ALIGN(8);
    *(.data*)
    . = ALIGN(8);
    __global_pointer$ = . + 0x800;
    *(.sdata*)
    . = ALIGN(8);
    __data_end = .;
  }} > TCDM AT> ROM

  __data_load_start = LOADADDR(.data);

  . = ALIGN(8);
  __bss_start = .;
  .sbss : {{ *(.sbss*) }} > TCDM
  .bss  : {{ *(.bss*) *(COMMON) }} > TCDM
  . = ALIGN(8);
  __bss_end = .;

  /* Per-core stacks at the top of TCDM: core i runs on
   * (__stack_region + (i + 1) * HES_CLUSTER_STACK_SIZE). */
  __stack_size = 0x{system.CLUSTER_STACK_SIZE:x};
  __stack_region = ORIGIN(TCDM) + LENGTH(TCDM) - 0x{stacks:x};

  /* Everything between .bss and the stacks is DMA scratch. */
  . = ALIGN(16);
  __heap_start = .;
  __heap_end = __stack_region;

  ASSERT(__heap_start <= __heap_end,
         "TCDM overflow: cluster data + bss leave no room for the stacks")
}}
"""


def memsys_expect() -> str:
    """Ranges the memory probe checks its measurements against.

    These are derived from the architecture, not from a previous run: the
    point is to catch a board where a level answers at the wrong level's cost
    -- a TCDM that replies at main-memory latency, a main memory that replies
    in a cycle, a cluster window that got mapped through the host's caches.
    They are deliberately wide, because the exact cycle count also carries ISS
    pipeline effects that are not part of the memory system's specification;
    what must hold is the separation between levels.
    """
    dram = memsys.DRAM_LATENCY
    return f"""{_GENERATED_BY}
#ifndef MEMSYS_EXPECT_H
#define MEMSYS_EXPECT_H

/* Host-side ranges. Only the L1 figure is asserted, and only as a sanity
 * bound: the CVA6 model charges a dependent load nothing for a D$ miss, so
 * the host cannot measure the levels below it. The cluster ranges below are
 * the ones that actually pin the memory system down. */
#define EXPECT_HOST_L1_LO                1
#define EXPECT_HOST_L1_HI                10

/* A miss all the way down pays DRAM_LATENCY ({dram}) plus the levels above it. */
#define EXPECT_HOST_DRAM_LO              {dram}
#define EXPECT_HOST_DRAM_HI              {dram * 4}

/* A cluster core's own TCDM is a single-cycle banked scratchpad one
 * interleaver crossing away. */
#define EXPECT_CLUSTER_TCDM_LO           1
#define EXPECT_CLUSTER_TCDM_HI           8

/* A cluster core reaching main memory goes out over the narrow AXI. */
#define EXPECT_CLUSTER_HBM_LO            {dram}
#define EXPECT_CLUSTER_HBM_HI            {dram * 4}

/* The host reaching a cluster TCDM. Reported by the probe but not asserted:
 * the CVA6 model does not stall a dependent load, so every level reads the
 * same loop-bound figure from the host side. Kept for reference. */
#define EXPECT_HOST_TCDM_LO              2
#define EXPECT_HOST_TCDM_HI              {dram - 1}

#endif /* MEMSYS_EXPECT_H */
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the header on disk is out of date")
    args = ap.parse_args()

    note = verify_offsets()
    content = render(note)

    expected = {HEADER: content, MESH / "host.ld": host_linker(),
                MESH / "memsys_expect.h": memsys_expect()}
    expected.update({MESH / f"{c.name}.ld": cluster_linker(c) for c in system.CLUSTERS})

    if args.check:
        for path, text in expected.items():
            current = path.read_text() if path.exists() else None
            if current != text:
                sys.exit(f"error: {path.relative_to(ROOT)} is out of date -- run "
                         f"python pipeline/gen_system_header.py")
        print(f"runtime/mesh generated files are up to date ({note})")
        return

    MESH.mkdir(parents=True, exist_ok=True)
    written = [(HEADER, content), (MESH / "host.ld", host_linker()),
               (MESH / "memsys_expect.h", memsys_expect())]
    written += [(MESH / f"{c.name}.ld", cluster_linker(c)) for c in system.CLUSTERS]
    for path, text in written:
        path.write_text(text)
    print(f"wrote {', '.join(str(p.relative_to(ROOT)) for p, _ in written)}")
    print(f"  ({note})")


if __name__ == "__main__":
    main()
