/* Generated by pipeline/gen_system_header.py from targets/hetero/system.py.
 * Do not edit: change the machine model and regenerate.
 *
 * peripheral offsets verified against GVSoC's regmap for: snitch, spatz
 */
#ifndef HES_SYSTEM_H
#define HES_SYSTEM_H


/* --- Main memory ------------------------------------------------------- */

#define HES_HBM_BASE                     0x80000000u
#define HES_HBM_SIZE                     0x80000000u
#define HES_DRAM_LATENCY                 100  /* cycles, main memory */

/* --- Per-ELF load windows ---------------------------------------------- */

#define HES_HOST_LOAD_BASE               0x80000000u
#define HES_HOST_LOAD_SIZE               0x04000000u
#define HES_SNITCH_LOAD_BASE             0x84000000u
#define HES_SNITCH_LOAD_SIZE             0x04000000u
#define HES_SPATZ_LOAD_BASE              0x88000000u
#define HES_SPATZ_LOAD_SIZE              0x04000000u

/* --- Host peripherals -------------------------------------------------- */

#define HES_STDOUT_BASE                  0xc0000000u
#define HES_CONTROL_REGS_BASE            0xd0000000u
#define HES_DRAM_BASE                    0xb0000000u
#define HES_HOST_HARTID                  16
#define HES_HOST_SCRATCH                 0x82000000u  /* free main memory past the host's image */
#define HES_HOST_SCRATCH_SIZE            0x02000000u

/* --- Cluster address map (relative to a cluster base) ------------------ */

#define HES_TCDM_OFFSET                  0
#define HES_TCDM_SIZE                    0x00020000u
#define HES_PERIPHERAL_OFFSET            0x00020000u
#define HES_ZERO_MEM_OFFSET              0x00030000u

/* --- Cluster peripheral registers -------------------------------------- */

/* Offsets from a cluster's peripheral base. The two variants declare a
 * different NumPerfCounters, so the scalar registers do not sit at the
 * same offset in both -- always use the ones for the cluster at hand. */
#define HES_CLUSTER_IRQ                  19  /* IRQ CL_CLINT_SET raises */
/* A readable peripheral register, at the same offset in both
   * variants, used only to check that the path answers. */
#define HES_PERIPH_PERF_COUNTER_PROBE    0x000u

/* --- The clusters ------------------------------------------------------ */

/* snitch: 9 cores, Snitch + FP subsystem (Xssr/Xfrep) */
#define HES_SNITCH_BASE                  0x10000000u
#define HES_SNITCH_TCDM                  0x10000000u
#define HES_SNITCH_PERIPH                0x10020000u
#define HES_SNITCH_NB_CORE               9
#define HES_SNITCH_DMA_CORE              8
#define HES_SNITCH_CTRL_CORE             8  /* == DMA core: only it can issue Xdma */
#define HES_SNITCH_NB_COMPUTE            8
#define HES_SNITCH_REQUIRES_STAGING      0  /* 1: kernels only see cluster-local memory */
#define HES_SNITCH_FIRST_HARTID          0
#define HES_SNITCH_LOAD_SCRATCH          0x86000000u  /* free main memory past this cluster's image */
#define HES_SNITCH_LOAD_SCRATCH_SIZE     0x02000000u
#define HES_SNITCH_CL_CLINT_SET          0x180u
#define HES_SNITCH_CL_CLINT_CLEAR        0x188u
#define HES_SNITCH_HW_BARRIER            0x190u
#define HES_SNITCH_PERF_COUNTER          0x100u
#define HES_SNITCH_PERF_COUNTER_ENABLE   0x000u
#define HES_SNITCH_NB_PERF_COUNTERS      16

/* spatz: 2 cores, Snitch + Spatz VPU */
#define HES_SPATZ_BASE                   0x00100000u
#define HES_SPATZ_TCDM                   0x00100000u
#define HES_SPATZ_PERIPH                 0x00120000u
#define HES_SPATZ_NB_CORE                2
#define HES_SPATZ_DMA_CORE               0
#define HES_SPATZ_CTRL_CORE              0  /* == DMA core: only it can issue Xdma */
#define HES_SPATZ_NB_COMPUTE             1
#define HES_SPATZ_REQUIRES_STAGING       1  /* 1: kernels only see cluster-local memory */
#define HES_SPATZ_FIRST_HARTID           9
#define HES_SPATZ_LOAD_SCRATCH           0x8a000000u  /* free main memory past this cluster's image */
#define HES_SPATZ_LOAD_SCRATCH_SIZE      0x02000000u
#define HES_SPATZ_CL_CLINT_SET           0x030u
#define HES_SPATZ_CL_CLINT_CLEAR         0x038u
#define HES_SPATZ_HW_BARRIER             0x040u
#define HES_SPATZ_PERF_COUNTER           0x020u
#define HES_SPATZ_PERF_COUNTER_ENABLE    0x000u
#define HES_SPATZ_NB_PERF_COUNTERS       2


/* --- Job mailbox ------------------------------------------------------- */

#define HES_MAILBOX_OFFSET               0
#define HES_MAILBOX_SIZE                 0x200u
#define HES_MAILBOX_MAX_ARGS             16
#define HES_CLUSTER_STACK_SIZE           0x00001000u

/* --- Engine ids -------------------------------------------------------- */

#define HES_ENGINE_CVA6                  0
#define HES_ENGINE_SNITCH                1
#define HES_ENGINE_SPATZ                 2
#define HES_NB_ENGINES                   3

#endif /* HES_SYSTEM_H */
