/* Generated by pipeline/gen_system_header.py from targets/hetero/system.py.
 * Do not edit: change the machine model and regenerate.
 */
#ifndef MEMSYS_EXPECT_H
#define MEMSYS_EXPECT_H

/* Host-side ranges. Only the L1 figure is asserted, and only as a sanity
 * bound: the CVA6 model charges a dependent load nothing for a D$ miss, so
 * the host cannot measure the levels below it. The cluster ranges below are
 * the ones that actually pin the memory system down. */
#define EXPECT_HOST_L1_LO                1
#define EXPECT_HOST_L1_HI                10

/* A miss all the way down pays DRAM_LATENCY (100) plus the levels above it. */
#define EXPECT_HOST_DRAM_LO              100
#define EXPECT_HOST_DRAM_HI              400

/* A cluster core's own TCDM is a single-cycle banked scratchpad one
 * interleaver crossing away. */
#define EXPECT_CLUSTER_TCDM_LO           1
#define EXPECT_CLUSTER_TCDM_HI           8

/* A cluster core reaching main memory goes out over the narrow AXI. */
#define EXPECT_CLUSTER_HBM_LO            100
#define EXPECT_CLUSTER_HBM_HI            400

/* The host reaching a cluster TCDM. Reported by the probe but not asserted:
 * the CVA6 model does not stall a dependent load, so every level reads the
 * same loop-bound figure from the host side. Kept for reference. */
#define EXPECT_HOST_TCDM_LO              2
#define EXPECT_HOST_TCDM_HI              99

#endif /* MEMSYS_EXPECT_H */
